name: Render Automation

on:
  schedule:
    - cron: "0 3 * * *"   # 03:00 UTC (00:00 no Brasil - suspender)
    - cron: "0 9 * * *"   # 09:00 UTC (06:00 no Brasil - reativar)
  workflow_dispatch:

jobs:
  control-render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install
        working-directory: render-automation

      - name: Decide action
        id: decide
        run: |
          hour=$(date -u +"%H")
          echo "Hora UTC: $hour"
          if [[ "$hour" == "03" ]]; then
            echo "::set-output name=action::suspend"
          elif [[ "$hour" == "09" ]]; then
            echo "::set-output name=action::resume"
          else
            echo "::set-output name=action::none"
          fi

      - name: Print env variables
        if: steps.decide.outputs.action != 'none'
        run: |
          echo "SERVICE_ID: $SERVICE_ID"
          echo "API_KEY: ***"
        env:
          SERVICE_ID: ${{ secrets.SERVICE_ID }}
          API_KEY: ${{ secrets.API_KEY }}

      - name: Run automation script
        if: steps.decide.outputs.action != 'none'
        run: node index.js ${{ steps.decide.outputs.action }}
        working-directory: render-automation
        env:
          SERVICE_ID: ${{ secrets.SERVICE_ID }}
          API_KEY: ${{ secrets.API_KEY }}
