name: Render Automation

on:
  schedule:
    - cron: "0 3 * * *"   # executa todo dia às 03:00 UTC (00:00 no Brasil se estiver -3)
    - cron: "0 9 * * *"   # executa todo dia às 09:00 UTC (06:00 no Brasil)
  workflow_dispatch: # permite rodar manualmente

jobs:
  control-render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run automation script
        run: node index.js
        env:
          SERVICE_ID: ${{ secrets.SERVICE_ID }}
          API_KEY: ${{ secrets.API_KEY }}
